"""
Gabarits de prompts pour l'Assistant IA. Deux modes strictement séparés,
jamais mélangés dans un même appel :

- PATIENT MODE : le modèle répond UNIQUEMENT à partir du contexte clinique
  structuré fourni (aucune connaissance médicale générale injectée ici,
  pour éviter qu'un savoir non vérifié pour ce cas précis ne se mélange
  à des données réelles de patient).

- GENERAL MODE (RAG) : le modèle répond à partir des passages récupérés
  dans la base documentaire, avec citation systématique des sources,
  jamais de connaissance "de mémoire" non sourcée.
"""

DISCLAIMER = (
    "This information is generated by an AI assistant to support clinical "
    "decision-making. It does not replace the judgment of a healthcare "
    "professional."
)

# ---------------------------------------------------------------------------
# Mode patient
# ---------------------------------------------------------------------------

PATIENT_SYSTEM_PROMPT = """You are a clinical AI assistant embedded in a hospital information system.
You answer a doctor's question about ONE SPECIFIC PATIENT, using ONLY the
structured clinical data provided below (symptoms, history, vitals, NLP
entities, risk score). Never invent facts that are not in this data. If the
data does not contain the answer, say so explicitly instead of guessing.
Never state a diagnosis; explain the available signals and let the
clinician draw conclusions. Answer in the same language as the question.
Keep the answer concise and clinically structured (bullet points where
useful)."""


def build_patient_prompt(question: str, context: dict) -> str:
    intake = context.get("intake")
    risk = context.get("risk")
    entities = context.get("entities", [])
    patient = context["patient"]

    lines = [PATIENT_SYSTEM_PROMPT, "", "### Patient clinical context"]
    lines.append(f"- Gender: {patient['gender']}, DOB: {patient['date_of_birth']}")

    if intake:
        lines += [
            f"- Reason for visit: {intake['reason_for_visit']}",
            f"- Reported symptoms (raw text): {intake['symptoms_text']}",
            f"- Medical history: {intake['medical_history'] or 'none reported'}",
            f"- Current medications: {intake['current_medications'] or 'none reported'}",
            f"- Allergies: {intake['allergies'] or 'none reported'}",
            f"- Vitals: T={intake['temperature']}\u00b0C, BP={intake['blood_pressure']}, "
            f"HR={intake['heart_rate']} bpm, SpO2={intake['oxygen_saturation']}%",
        ]
    else:
        lines.append("- No admission on file for this patient yet.")

    if entities:
        present = [e["value"] for e in entities if not e["negated"]]
        negated = [e["value"] for e in entities if e["negated"]]
        lines.append(f"- NLP entities detected as PRESENT: {', '.join(present) or 'none'}")
        lines.append(
            f"- NLP entities explicitly DENIED by the patient "
            f"(excluded from the risk score): {', '.join(negated) or 'none'}"
        )

    if risk:
        lines += [
            f"- Risk score: {risk['score']}/100 ({risk['level']})",
            f"- Risk explanation (rule-based engine): {risk['explanation']}",
            f"- Model confidence: {risk['confidence']}",
        ]
    else:
        lines.append("- No risk assessment available for this admission yet.")

    lines += ["", "### Doctor's question", question, "", "### Answer"]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Mode général (RAG)
# ---------------------------------------------------------------------------

GENERAL_SYSTEM_PROMPT = """You are a medical knowledge assistant. Answer the
question using ONLY the excerpts provided below, taken from the clinic's
reference documents. Cite the source of every claim using [Source N]. If
the provided excerpts do not contain enough information to answer, say so
explicitly instead of relying on prior knowledge. Never provide a specific
diagnosis or treatment plan for a real patient; give general medical
information only. Answer in the same language as the question."""


def build_general_prompt(question: str, retrieved_chunks: list[dict]) -> str:
    lines = [GENERAL_SYSTEM_PROMPT, "", "### Reference excerpts"]
    for i, chunk in enumerate(retrieved_chunks, start=1):
        lines.append(f"[Source {i}: {chunk['source']}]\n{chunk['text']}\n")
    lines += ["### Question", question, "", "### Answer"]
    return "\n".join(lines)
